"""Add ast table

Revision ID: c324890dc081
Revises: 65a110c12266
Create Date: 2026-10-09 13:40:01.970341

"""
from alembic import op
import sqlalchemy as sa
from typing import Sequence, Union


revision: str = 'c324890dc081'
down_revision: Union[str, Sequence[str], None] = '65a110c12266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ast',
    sa.Column('ast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specimen_id', sa.Text(), nullable=False),
    sa.Column('organism_name', sa.Text(), nullable=True),
    sa.Column('antibiotic', sa.Text(), nullable=True),
    sa.Column('ast_method', sa.Text(), nullable=True),
    sa.Column('susceptibility', sa.Text(), nullable=True),
    sa.Column('sensitivity_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['specimen_id'], ['isolates.specimen_id'], ),
    sa.PrimaryKeyConstraint('ast_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ast')
    # ### end Alembic commands ###
